Started by upstream project "[8mha:////4N+xKAmskkIjiAKi7Ga0bQ6psYNpIm20xSKMddamLXXhAAAAnh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzeEgZh/az8JH3fRKD2ioCi/KzU5BJ9ACRKKtTIAAAA[0mMatrixProject" build number [8mha:////4JXYjcYRmEABce/V22D6jRANV7Znnx0FCrv3tr0/nC/IAAAAoB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAymEgZR/az8JH3fRKD2ioCi/KzU5BJ9YwsAzGf7asoAAAA=[0m38
originally caused by:
 Started by user [8mha:////4BZv/RbSRYtMZa6Gy4V7aSsv1Lgf4frwfCHza6l7zHyjAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Building remotely on [8mha:////4OBFeFMOzx8ebCRFsuyvnDSm4reWEDKuXaUDzvkUHO5SAAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy2EgYB/eT83ILSktQi/eKcxLJUYwAUl24cxQAAAA==[0mslave3 (label2) in workspace C:\Jenkins\workspace\MatrixProject\label\slave3
 > git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git.exe config remote.origin.url https://github.com/OlegGlizerin/TeamRepo.git # timeout=10
Fetching upstream changes from https://github.com/OlegGlizerin/TeamRepo.git
 > git.exe --version # timeout=10
 > git.exe fetch --tags --progress https://github.com/OlegGlizerin/TeamRepo.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision fb6100a51c82ef5b477b7389c077b0f0fc486f22 (refs/remotes/origin/oleg)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f fb6100a51c82ef5b477b7389c077b0f0fc486f22
Commit message: "test without datorama"
 > git.exe rev-list fb6100a51c82ef5b477b7389c077b0f0fc486f22 # timeout=10
[slave3] $ cmd.exe /C "c:\Python27\python.exe C:\Users\JACKSP~1\AppData\Local\Temp\shiningpanda8612394835205820258.py && exit %%ERRORLEVEL%%"
Traceback (most recent call last):
  File "C:\Users\JACKSP~1\AppData\Local\Temp\shiningpanda8612394835205820258.py", line 50, in <module>
    configNewXmlByMachine()
  File "C:\Users\JACKSP~1\AppData\Local\Temp\shiningpanda8612394835205820258.py", line 28, in configNewXmlByMachine
    numOfThreads = int(getNumOfThreadsFromXml())
  File "C:\Users\JACKSP~1\AppData\Local\Temp\shiningpanda8612394835205820258.py", line 12, in getNumOfThreadsFromXml
    root = getTreeXml(Xmlfilepath).getroot()
  File "C:\Users\JACKSP~1\AppData\Local\Temp\shiningpanda8612394835205820258.py", line 7, in getTreeXml
    with open(pathToXml,"rb") as f :
IOError: [Errno 2] No such file or directory: '\\AutomationParallel3TestsExcercise\\src\\main\\resources\\methods-test-testng.xml'
Build step 'Custom Python Builder' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
